### ISSUE TITLE
Data package?

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/spanishoddata#1]
Heads-up @e-kotov and @eugenividal, I'm reviving this after failed attempts a few years ago..

Could it be worth making a small package to make this dataset easier to use, along the lines of stats19 and geobr?

**Comment by Robinlovelace** [comment]
cc @e-kotov you're in: https://github.com/Robinlovelace/spanish_od_data/invitations

**Comment by e-kotov** [comment]
@Robinlovelace added some draft code to
1. get their xml
2. download files
3. check for updates in xml and update missing files
4. convert to geopackage (for spatial data), duckdb with ENUMs (for space saving and speed, hopefully) and arrow/parquet

https://github.com/Robinlovelace/spanish_od_data/tree/main/draft-code

**Comment by Robinlovelace** [comment]
Amazing, thank you!

**Comment by eugenividal** [comment]
Hi @Robinlovelace and @e-kotov, sounds good. I have no experience creating R packages, but I would love to learn and the data set is of interest to me.
