### ISSUE TITLE
move SQL queries from code to text sql files

### ISSUE THREAD

**Issue by e-kotov** [Robinlovelace/spanishoddata#22]

**Comment by Robinlovelace** [comment]
Big 👍 to this. https://www.reddit.com/r/Python/comments/my1m66/stop_hardcoding_and_start_using_config_files/ is a Reddit thread on general concept, never seen '.sql files and config' but see no reason not and makes sense as it's as 'close to the metal' as possible for any system to import the datasets will likely involve software that can read SQL.

**Comment by e-kotov** [comment]
Seems like if we keep the sql queries as as, that is with placeholders (e.g. `{csv_folder}`) in curly braces to be replaced with `glue::glue()`, e.g.:

```sql
"CREATE VIEW od_csv_raw AS SELECT *
          FROM read_csv_auto('{csv_folder}**/*.txt.gz', delim='|', header=TRUE, hive_partitioning=TRUE,
          columns={{
            'fecha': 'DATE',
            'origen': 'VARCHAR',
            'destino': 'VARCHAR',
            'periodo': 'INTEGER',
            'distancia': 'VARCHAR',
            'viajes': 'DOUBLE',
            'viajes_km': 'DOUBLE'
          }},
          dateformat='%Y%m%d');"
```


The code in python will look like this (which is not too bad):

```python
# Load SQL query from file
with open('query.sql', 'r') as file:
    sql_query = file.read()

# Replace the {csv_folder} placeholder with the actual value
csv_folder = "/path/to/csv_folder"
sql_query = sql_query.replace("{csv_folder}", csv_folder)

```

Python's own [`Jinja2`](https://jinja.palletsprojects.com/en/3.1.x/api/#basics:~:text=Template(%27Hello%20%7B%7B%20name%20%7D%7D!%27).stream(name%3D%27foo%27).dump(%27hello.html%27)) uses double curly braces, but in R's `glue` that would just escape the braces and make `glue` interpret double curly braces as single, breaking the whole thing down. So no single beautiful solution for both languages. But that's not critical, esp. at the moment. We can always change it later, for now let's focus on R.

**Comment by Robinlovelace** [comment]
Sounds like a good solution that would make it clear where hard-coded categorisation/config files live and reduce R-Python-Other translation efforts.

**Comment by Robinlovelace** [comment]
🔥
