### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/spanishoddata#30]
Woops, seems I accidentally deleted the old one. Can you regenerate it @e-kotov ?

**Comment by e-kotov** [comment]
@Robinlovelace trying right now

**Comment by e-kotov** [comment]
wow, there are quite a few packages and a lot of data that needs to be downloaded for that README ).


A bit confused by:

https://github.com/Robinlovelace/spanishoddata/blob/3c9f06a281ac4690a20dbbc98995733dd942eab0/README.qmd#L198-L207

My idea was that we will replace the original `spod_get()` with the `spod_get_od()`. So the 'negative' example that highlights the package benefits would be a more detailed spaghetti  code that one would need without the package.

**Comment by e-kotov** [comment]
Fix with #32 .

**Comment by Robinlovelace** [comment]
> My idea was that we will replace the original `spod_get()` with the `spod_get_od()`. So the 'negative' example that highlights the package benefits would be a more detailed spaghetti code that one would need without the package.

Yes, `spod_get()` should be removed.

**Comment by Robinlovelace** [comment]
Big 👍 to simplifying the example in the README, we can split-out the stuff that requires the extra deps to an unevaluated vignette.

**Comment by e-kotov** [comment]
> Yes, `spod_get()` should be removed.

Good. At some point.
