### ISSUE TITLE
Tidy-up documentation

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/spanishoddata#31]
As discussed with @eugenividal, the package could benefit from some checks of the writing in the documentation. For example, does everything here read-well and make sense?

Also, we can use this issue to discuss any issues with the function documentation, which can be found in links here: https://robinlovelace.github.io/spanishoddata/reference/index.html

**Comment by eugenividal** [comment]
Hi @Robinlovelace, here are some issues I’ve seen while trying to set up the project on my computer:

- It is a pity that the MITMA page on the data does not have an English version. That is why I think the information in the intro on the data should be more detailed. One important thing you forgot to mention is that the data is based on the position of mobile phones.

- I got some problems when trying to render the .qmd file.  

    • First, I had to manually install the ‘osmactive’ package using “remotes::install_github("nptscot/osmactive")”

    • Second, I was asked to install the ‘odjitter’ package too, but unfortunately I could not. I followed this command: `cargo install --git https://github.com/dabreegster/odjitter` but got the error below (not sure why since I had no problem using this package for the 'cruse' project).
      
![image](https://github.com/user-attachments/assets/710f4dcc-a0be-48c5-a289-e6a5a3f9f469)
        	(I do not know how to set the environment variable `CARGO_TARGET_DIR` to that path).

- The previous issue with the packages makes me wonder whether the part after disaggregating desire is not a bit out of the scope of the package. Don't get me wrong I love the last visualisation and the odjittering stuff but perhaps it makes it too complex for not advanced users. 

- I also had some issues understanding the installation and setting the directory instructions. Why load the package locally? Also terms like "Set globally/locally", "on a per session", and "set the ‘envar'’’, sound a bit Greek to me.

I will carry on checking the document tomorrow after trying to fix the 'odjitter' package issue.

**Comment by e-kotov** [comment]
> * I also had some issues understanding the installation and setting the directory instructions. Why load the package locally? Also terms like "Set globally/locally", "on a per session", and "set the ‘envar'’’, sound a bit Greek to me.

Super useful comment, I'm all for simplifying the language of instructions and the preparation steps. Would you prefer a function like:

```r
spod_set_cache_directory("path/to/where/you/want/to/store/the-files")
```

That would just set whatever is needed in whatever file or environment that needs to be set? (And we would move the instructions for expert users into some vignette on advanced use).

Or perhaps:
```r
options(spanishoddata.cache_folder = "path/to/where/you/want/to/store/the-files")
```




> * Don't get me wrong, I love the last visualisation and the odjittering stuff, but perhaps this routing part (which requires sophisticated packages) is too complex for most users.

Perhaps we could do just a vis of raw flows (though this package is also not on CRAN yet): https://github.com/JohMast/flowmapper and move the cool disaggregation stuff into an advanced vignette. But we can also keep the disaggregation vis in the main README as an inserted png and a teaser for the advanced vignette.

**Comment by Robinlovelace** [comment]
Agree re. moving advanced stuff out of the README, now tracked in #39. Would welcome any other updates to the README and other bits of documentation, thanks Eugeni, any questions welcome.

**Comment by eugenividal** [comment]
Hi @e-kotov, thanks for your comments. I am a data analyst, not a programmer. I conduct statistical data analyses using R, but I haven't created a package or functions before. So, I believe my comments can help make the package easier to understand for people who are not very tech-savvy.

I’ve seen you moved the "disaggregating desire lines" part to an advanced vignette. I like that. The README is now simpler and straight to the point, which I understand to be providing interested people with Spanish OD data "in analysis-ready formats." Not sure whether the https://github.com/JohMast/flowmapper would help. Often less can be more. 

There are still some parts in the README that I find challenging to understand. 

1) Installation. I wonder why people would load the package locally. I suppose if someone does it (perhaps to make improvements to the package?) they will know how to clone a repository, am I correct? (So, perhaps this is not necessary in the README) – please correct me if I am wrong! Also, I ran this command in my terminal and failed: I got the following message:

```
warning: templates not found /usr/share/git-core/templates
fatal: Unable to find remote helper for 'https'
exit status 128
Command 'code' not found, but can be installed with:
sudo snap install code
```
Not sure which could be the problem.

2) Setting the data directory. In the intro, you state “If you want to use many of the data files, it’s recommended you set a data directory”. So, I understand this part is necessary. However, I struggle to understand the difference between setting a directory globally and locally, and also setting them up.
If I follow the steps to set up the directory globally I get the error: 
```
Error in spod_available_data(ver = 2) : 
  could not find function "spod_available_data" in line, when getting the metadata.
```

Also, in this comment `# Then set the data directory globally, by typing this line in the file` I would specify which file you mean as follows: (# Then set the data directory globally, by typing this line in the (.Renviron) file (that pops up).

I do not know how to set up the directory locally either. Perhaps this new function `spod_set_cache_directory` you mention above would make things easier.  

I hope this helps. I will have a look at the functions documentation next week.

**Comment by e-kotov** [comment]
@eugenividal 


> So, I believe my comments can help make the package easier to understand for people who are not very tech-savvy.

That's exactly the point! So please do keep the criticism coming.




> 1. Installation. I wonder why people would load the package locally.

Actually there is no point unless you are developing or debugging it. We should definitely remove it.

This should suffice for the setup:
```r
if (!require("remotes")) install.packages("remotes")
remotes::install_github("Robinlovelace/spanishoddata")
library(spanishoddata)
```

Please, skip anything else about cloning and stuff.





> 2\. Setting the data directory.

## `.Renviron` File Precedence in R

If a local `.Renviron` file is present in the working directory of an R session, it will override the global `.Renviron` file located in the user's home directory. Here's how it works:

### Types of `.Renviron` Files

1. **Global `.Renviron`**: 
   - Located in the user's home directory (typically `~/.Renviron`).
   - Sets environment variables that are applied globally across all R sessions for that user.

2. **Local `.Renviron`**: 
   - Located in the working directory of a specific R project or session.
   - Sets environment variables specific to that project or session.

### Priority Order

When R starts, it checks for `.Renviron` files in the following order:

1. **Local `.Renviron`**: 
   - If a local `.Renviron` file is found in the current working directory, it is read first.
   - The variables set here take precedence over those set in the global `.Renviron` file.

2. **Global `.Renviron`**: 
   - If no local `.Renviron` is found, R will read from the global `.Renviron` file in the user's home directory.

### Summary

- **Local `.Renviron`** file settings override the global settings.
- This behavior allows project-specific settings without affecting other R projects or sessions.

So if you are working with this large dataset in multiple projects, you may want to just set this path for downloaded files globally. But I agree, that seems to be too much details and too much new stuff to learn, and a simpler solution would be a reasonable default.

So I would say we provide a function or an option and move away any more complicated options into a separate vignette or under foldable section of the readme.





> could not find function "spod_available_data" in line, when getting the metadata.

Sorry about that, I have "hidden" this function in the last update by accident. Will return in in the next update coming this week.

@eugenividal I will update the README tomorrow following your comments. I will let you know when things are fixed. Thank you!

**Comment by Robinlovelace** [comment]
Quick response to one thing you said Eugeni:

> Not sure whether the https://github.com/JohMast/flowmapper would help. IMO, often, less is more.

Could be great to add an example using the pkg for visualisation in the `uses.qmd` vignette. Loads of good ideas, interested to see what Egor thinks. Feedback + contributions v. welcome.

**Comment by Robinlovelace** [comment]
> We should definitely remove it.

Let's keep it in a hidden and un-evaluated chunk is my suggestion. Agreed though Eugeni, not helpful for 99% of readers.

**Comment by Robinlovelace** [comment]
Great to have the 'tires kicked' on the project, will round off lots of rough edges so-to-speak!

**Comment by eugenividal** [comment]
Thanks @e-kotov for the clear explanations and both for the comments. Sorry, I said I would have a look at the functions documentation tomorrow or Monday, but it will have to wait until Tuesday or Wednesday. I am cycling to my parents tomorrow to spend a few days and can't bring my laptop with me. It is a 100 km ride 🤪 I hope that's Ok.

**Comment by e-kotov** [comment]
@eugenividal no worries, whenever you are ready!

**Comment by eugenividal** [comment]
@Robinlovelace @e-kotov 

I just had a look at the README and the PACKAGE INDEX documentation and have some comments:

README: 
1) Instead of 'Estudios basicos' as a subheading, I suggest using something like 'OD data'. We should explain that we are obtaining the OD data and why the object is tbl_dbi instead of a data frame. I guess this is because the datasets are huge and cannot be stored on a computer. Am I correct?
2) In the same subsection, I didn't understand the part where you mentioned "see how you could do this manually with the following code, highlighting the benefits of the package." Did you mean "see how you could do the same without the help of the package"?
3) I would include the "od" package in a final references section.

PACKAGE INDEX:
1) Some functions seem a bit confusing. What do the different versions mean? Is this explained somewhere? What is duckdb? Also, what’s the difference between spod_download_data(), spod_get(), and spod_get_od()?
2) I noticed a couple of typos: replace 'retrieves' with 'retrieve' and 'mobiltiy' with 'mobility.' in the Package index main page.
3) Are there any formatting functions available? I haven't looked at the raw data.

I hope it helps

**Comment by Robinlovelace** [comment]
Agreed, these are great comments Eugeni, will check out your PR.

**Comment by eugenividal** [comment]
This can be closed now.
