### ISSUE TITLE
Mention the two versions in the README intro

### ISSUE THREAD

**Issue by eugenividal** [Robinlovelace/spanishoddata#47]
Mention very briefly and clear in the README intro the two versions of the data and direct the readers to the respective vignettes.

**Comment by eugenividal** [comment]
New intro README:

spanishoddata provides functions for downloading and formatting Spanish origin-destination (OD) data from the Ministry of Transport and Sustainable Mobility of Spain.

It supports the two versions of the Spanish OD data: Open Data Movilidad 2020-2021 and Open Data Movilidad from 2022. [The first released between 2001 and 2020](https://www.transportes.gob.es/ministerio/proyectos-singulares/estudios-de-movilidad-con-big-data/estudios-de-movilidad-anteriores/covid-19/opendata-movilidad); and the second version disponible desde enero de 2022, los resultados de la cual se publican mensualmente (hacia el día 15 de cada mes) (https://www.transportes.gob.es/ministerio/proyectos-singulares/estudios-de-movilidad-con-big-data/estudio-basico-diario).

Both versions are primarily sourced from mobile phone positioning data and include matrices for overnight stays, individual movements, and trips of Spanish residents at different geographical and temporal levels.

spanishoddata is designed to save people time by providing the data in analysis-ready formats. Automating the process of downloading, cleaning and importing the data can also reduce the risk of errors in the laborious process of data preparation. It also reduces computational resources by using computationally efficient packages behind the scenes. To effectively work with multiple data files, it’s recommended you set up a data directory where the package can search for the data, and download only the files that are not already present.

**Comment by e-kotov** [comment]
@eugenividal good to go, feel free to merge. Please, connect your recent pull request with any issues it closes via # sign and close the issues.
