### ISSUE TITLE
Typos in the Package index main page

### ISSUE THREAD

**Issue by eugenividal** [Robinlovelace/spanishoddata#50]
Typos in the Package index main page: replace 'retrieves' with 'retrieve' and 'mobiltiy' with 'mobility.'.

**Comment by e-kotov** [comment]
@Robinlovelace please fix the typos in the repo metadata (the one that's on the right on repo homepage on github), i don't have access to this

**Comment by Robinlovelace** [comment]
Will do.

**Comment by Robinlovelace** [comment]
> @Robinlovelace please fix the typos in the repo metadata (the one that's on the right on repo homepage on github), i don't have access to this

Can you be more specific?

**Comment by Robinlovelace** [comment]
It's currently:

Access national high-quality and open-access datasets on movement patterns derived from mobile telephone datasets

**Comment by e-kotov** [comment]
> Can you be more specific?

ah, my eyesight let me down. the keywords are correct
![Screenshot 2024-08-27 at 13 57 29](https://github.com/user-attachments/assets/38aea2d6-14d6-4852-95ee-8ffcffa78b8c)

otherwise, fixed in the package with #59
