### ISSUE TITLE
package name

### ISSUE THREAD

**Issue by e-kotov** [Robinlovelace/spanishoddata#58]
@Robinlovelace , as rightfully [noted](https://github.com/Robinlovelace/spanishoddata/pull/52#discussion_r1730773293) by @eugenividal , the package actually provides access to more than od data, especially for v2 2022 onwards data:
- complete studies: https://www.transportes.gob.es/ministerio/proyectos-singulares/estudios-de-movilidad-con-big-data/estudios-completos
- routes: https://www.transportes.gob.es/ministerio/proyectos-singulares/estudios-de-movilidad-con-big-data/rutas-por-carretera

What do you think about name change to `spanishmobilitydata` (functions with prefix `spmd_`), `spainmobility` (prefix `sm_` or `smob_`). Or go wild with `esmovilidad` (`esmv_`). Other options?

**Comment by eugenividal** [comment]
My suggestion was `spanishmobilidata`, is this not possible? `esmovilidad` (It is mobility) sounds good. Others that comes to my mind are `mobilidatos` or `esmobilidata`

**Comment by e-kotov** [comment]
Ah, so `es` in `esmovilidad` would refer to both `España` and `es` (=is). Cool! I would refrain from mixing languages, e.g. mobilidatos is neither in English nor Spanish, but a weird mix of both. And to my taste "mobili" shortening is so-so, even though obviously shorter than "mobility".

**Comment by eugenividal** [comment]
Mixing languages is more Esperanto :). Your choice guys. All the suggestions sound good to me. Even `spanishoddata` can still be fine by me. It is more catchy but it does not represent all the actual data that contains, which is not a big deal.

**Comment by Robinlovelace** [comment]
Thoughts on each...

- spanishoddata, simple, easily understood (and one would expect OD data package to contain the boundaries)
- spanishmobilitydata, no big difference but longer, and as Egor said the datasets can be used for fields beyond mobility
- spainmobility, no big difference but doesn't sound great to me
- esmovilidad, not a fan
- spanishmobilidata sounds fine but longer and a bit clunky
- mobilidatos too generic
- esmobilidata not as clear what it is

If I were starting from a blank page spanishoddata would get my vote so would suggest keeping it as is.

**Comment by e-kotov** [comment]
> * esmovilidad, not a fan

come on, that one is so cool and poetic)

**Comment by Robinlovelace** [comment]
> > * esmovilidad, not a fan
> 
> come on, that one is so cool and poetic)

OK, could be convinced, if you and @eugenividal like it, may need I need to reschedule some comms if so tho..

**Comment by e-kotov** [comment]
`esmovilidad` is really growing on me, still have a bit of time to think it through. `esmovilidad` also celebrates the fact that it is data from Spain. Is it too much of a tongue and mind twister for a non-Spanish speaker?

**Comment by eugenividal** [comment]
The thing is that the package contains tables that are not origin/destination apart from the spatial boundaries, for example, all the tables of [maestra2-mitma](https://www.transportes.gob.es/ministerio/proyectos-singulares/estudios-de-movilidad-con-big-data/estudios-de-movilidad-anteriores/covid-19/opendata-movilidad). Although I agree that the OD data is by far the most relevant.
My favorite is `spanishmobilidata` :) I like `esmovilidad`, but the one I find the most catchy is `spanishoddata`. I wouldn't change it at the moment unless there is a clear consensus.
Perhaps we can reconsider once the importance of the OD data in the package becomes completely clear.

Another thing we could do is limit the data in the package to just the OD data (which seems the most relevant) and the boundaries. Would this make the package easier to manage and understand? I know that the name should not define the project, but the other way around. However, perhaps the other data is less relevant and removing it would make the package lighter and easier to understand.

Sorry for bringing up these (probably fruitless) discussions at this stage of the package creation.

**Comment by e-kotov** [comment]
`{spanishoddata}`

**Comment by Robinlovelace** [comment]
😌

**Comment by Robinlovelace** [comment]
Less disruption: good!
