### ISSUE TITLE
logo size

### ISSUE THREAD

**Issue by e-kotov** [Robinlovelace/spanishoddata#61]
Logo is huge on the pkgdown website: https://robinlovelace.github.io/spanishoddata/index.html while it is normal size on the github readme: https://github.com/Robinlovelace/spanishoddata/

**Comment by e-kotov** [comment]
I have no idea at the moment, how to fix this)

**Comment by e-kotov** [comment]
Closed by #62

**Comment by Robinlovelace** [comment]
Great to see the logo!

**Comment by Robinlovelace** [comment]
Social card added FYI @e-kotov 
![image](https://github.com/user-attachments/assets/24c8a982-68aa-43c7-81e2-f39351e34071)

**Comment by e-kotov** [comment]
Cheers!
