### ISSUE TITLE
Todo: Vignette showing how to aggregate the data for vis with flowmapper and flowmaps

### ISSUE THREAD

**Issue by e-kotov** [Robinlovelace/spanishoddata#63]
Our logo (will add the code to the repo soon) is made with https://github.com/JohMast/flowmapper
The original flows vis style is from https://github.com/FlowmapBlue/flowmapblue.R . Would be nice to have a vignette that shows how to aggregate data for these packages. `{flowmapper}` is now almost on CRAN (in second review), and I asked `flowmapblue.R` about plans too. Perhaps it would be good go have simple functions that prepare the data for these two tools.

**Comment by Robinlovelace** [comment]
Job done in #65 I think.
